### ISSUE TITLE
Please release 0.3.2

### ISSUE THREAD

**Issue by eggplants** [llvmenv/llvmenv#114]
I would like to use `llvmenv entry 12.0.0`. So please publish 0.3.2 or 0.3.2-alpha.0 to crates.io.

**Comment by eggplants** [comment]
`cargo install --git https://github.com/llvmenv/llvmenv` is bothersome for me.

**Comment by termoshtt** [comment]
https://github.com/llvmenv/llvmenv/releases/tag/v0.3.2
done
