### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by adambrangenberg** [llvmenv/llvmenv#129]
I'm installing version 12, but it fails

![image](https://github.com/llvmenv/llvmenv/assets/69903408/6fbbc0f0-e423-4bcd-86c1-c9a45881a9d9)

**Comment by wangboo** [comment]
I have the same build error right now, can you share some idea how to solve this problem?
my env are below:
clang version 16.0.6
gcc (GCC) 13.2.1 20230801
Operating System: Manjaro Linux                   
Kernel: Linux 6.6.19-1-MANJARO
Architecture: x86-64
